const pause_2 = Cypress.env('pause_2')
describe('Test Survey Form', function() {
    it('Visits Talk Over RA', function() {
      cy.visit('https://www.talkoverra.com') 
      Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      })

    cy.viewport(1280, 800)
    cy.wait(pause_2)
    cy.get('#truste-consent-button').click()
    cy.wait(pause_2)
    cy.get('[href="https://www.talkoverra.com/ca/en.html"]').click()
    cy.wait(pause_2)
    cy.get('ul > :nth-child(1) > a').click()
    cy.wait(pause_2)
    cy.get('.col-md-9 > .button-link > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-0 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-1 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(1) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-1 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-2 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-2 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(3) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-2 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(4) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-3 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(1) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-3 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-3 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(3) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-3 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(1) > .form-checkbox > :nth-child(4) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multiStep-3 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(2) > .form-checkbox > :nth-child(1) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-4 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(2) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multi-step-prev-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#multiStep-5 > .carousel-content > :nth-child(1) > :nth-child(1) > .col-12 > .center > .column-control > .column-control-wrapper > .bg-container > .container > .row > :nth-child(2) > .form-checkbox > :nth-child(2) > .form-check__inner > .form-check-label > .checkbox').click()
    cy.wait(pause_2)
    cy.get('#multi-step-next-btn > .btn').click()
    cy.wait(pause_2)
    cy.get('#downloadMultistepPdf > .btn').click()


    })
})